name: Deploy KW-Clustering to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true  # Récupère les sous-modules

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}  # IP du serveur
          username: ${{ secrets.VPS_USER }}  # Utilisateur SSH (ex: debian)
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Clé privée SSH
          script: |
            cd /var/www/seo-tools/clustering-kw
            git pull origin main
            docker compose up -d --build
